# Generated by Django 4.2 on 2023-04-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField(max_length=10)),
                ('begin_of_route', models.CharField(max_length=50)),
                ('travel_time', models.DurationField()),
            ],
        ),
    ]
