# Generated by Django 4.2 on 2023-04-29 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_city_options'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['-name'], 'verbose_name': 'Поїзд', 'verbose_name_plural': 'Поїзда'},
        ),
        migrations.AlterField(
            model_name='train',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='cities.city', verbose_name='Відправлення'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер поїзда'),
        ),
        migrations.AlterField(
            model_name='train',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='cities.city', verbose_name='Прибуття'),
        ),
        migrations.AlterField(
            model_name='train',
            name='travel_time',
            field=models.IntegerField(verbose_name='Час в дорозі'),
        ),
    ]
