# Generated by Django 4.2 on 2023-05-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0003_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_time', models.IntegerField(verbose_name='Час у дорозі')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва маршруту')),
                ('cities', models.ManyToManyField(blank=True, to='cities.city', verbose_name='Проміжні міста')),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_end_city_set', to='cities.city', verbose_name='Кінцеве місто')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_start_city_set', to='cities.city', verbose_name='Початкове місто')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
                'ordering': ['travel_time'],
            },
        ),
    ]
