# Generated by Django 4.2 on 2023-04-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-name'], 'verbose_name': 'Населений пункт', 'verbose_name_plural': 'Населені пункти'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Населений пункт'),
        ),
    ]
